# basic options
title: 
author: shuvayanb
email: your-email@domain.com
description: 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
#theme: minima

theme: jekyll-theme-slate
