# basic options
title: Home Page
author: Shuvayan Brahmachary
email: b.shuvayan@gmail.com
description: Shuvayan Brahmachary

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

